spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ticketer
    username: root
    password: ora123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: mysql
